### ISSUE TITLE
What do to about org.apache.ant?

### ISSUE THREAD

**Issue by merks** [eclipse-orbit/orbit-simrel#13]
It appears that org.apache.ant is the only EBR-based bundle that cannot be migrated.   Why is that?

Firstly the bundle has content that does not come from any Maven artifact.  

https://repo1.maven.org/maven2/org/apache/ant/

I.e., the bin and etc folder from this download

https://dlcdn.apache.org//ant/binaries/apache-ant-1.10.14-bin.zip

The bin and etc folders are copied from here

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/6729f14a-9ade-471a-b9da-7bc35d103c59)

as described here:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/03c6cc22-53ef-4cca-8618-c2eec5847af9)

It also has special EBR "instructions":

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/5fd9e776-c2ea-4760-8095-b623bbe06cd6)

That's because the Platform expects such an all-in-one bundle, separate libraries exactly as it is structure now (and like in the binary download).

@jonahgraham 

Should I try to create infrastructure to generate/automate all this---that is, stuff that doesn't use EBR---or shall we maintain EBR "forever" with this bundle as effectively the one and only usage?

**Comment by jonahgraham** [comment]
Third option is stop providing this "custom" Ant jar. That means changes to Eclipse platform's Ant integration and a notice for downstream consumers. I don't know how long the tentacles of Ant into Eclipse platform (and wider IDE) are, but in the same way we don't try to repackage Maven or Gradle to make them bundles (AFAIK!), maybe we should stop for Ant. I think the biggest issue is that Ant's integration runs in the same process as Eclipse IDE.

In addition. see discussion in https://github.com/eclipse-orbit/orbit/issues/17 which covers the out of compliance aspect of shipping Jai and the discussion on how we have to modify the contents of Ant to workaround security manager options.

**Comment by merks** [comment]
Certainly moving the problem to the consumer(s) is the easiest thing for Orbit to do.  But I suspect that I will need to help do most of that work for the Platform, and then not only will this be the path of most disruption but also I think it will be more work than the alternatives...  😱 

I've been experimenting with the following approach.  Take the binary download and "publish" it to a maven-compatible repository.  Mostly that's pretty trivial and while I've prototyped it manually, it is easily automated simply by following a well-defined name/version pattern in standard scaffolding:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/60e1817e-3075-457c-a24b-1eb3d3e40821)

The jar here is simply the binary zip with the root folder flatten out; later it can be filtered to clean out things (jai?) that aren't needed.  This can then be used the "normal" way in a *.target like this:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/35f8bd6d-becb-44da-a8c0-6ed8051537fe)

This does produce a jar that looks to be pretty much identical to what's already produced by EBR.   I'm pretty sure I can create a source.jar easily here too, and then we'd get everything we need structured like currently.   The most annoying aspect here is the URL needed to reference the location of the "ant maven"  repository from within the *.target file, which appears to have no support for anything other than an absolute URI.  

If I factored out the work to "publish to a Maven compatible repository" and promote that to download.eclipse.org, then I would have an https URI to use in the target platform...

**Comment by merks** [comment]
Here is a side-by-side comparison of the bundle manifests:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/1534df55-9b23-4b6c-a459-d49cc176d3c2)

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/01ec6f8f-b185-4443-a9d9-c5b621c9b105)

**Comment by jonahgraham** [comment]
@merks your approach is sound (and while I would love to ditch this, I agree that it is *probably* much more work to disentangle ant from platform)

> Take the binary download and "publish" it to a maven-compatible repository.

You can use this: https://ci.eclipse.org/orbit/job/upload-approved-artifacts/ which uploads to repo.eclipse.org already.

**Comment by merks** [comment]
@jonahgraham 

That was a great hint!  I investigated how that job works and it's really simple, doing **exactly** what I want.  I'm able to automate the creation based purely on the newest available version number of ant.

Now for the details.  Do I interpret correctly that we should/must create a jar that omits the jai.jar?  And that's the only other consideration?

**Comment by jonahgraham** [comment]
> Do I interpret correctly that we should/must create a jar that omits the jai.jar? 

That is correct (see this comment in iplab for those that want to know why https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5372#note_1051371)

> And that's the only other consideration?

EBR was falling over the latest versions of Ant, I assume that new infra doesn't fall over similarly. See [this comment from gerrit](https://git.eclipse.org/r/c/orbit/orbit-recipes/+/199491/comments/5eef089e_ce03c726) (with key part quoted here in case gerrit disappears):

> There is a new class in ant-launcher.jar in the default package called allow (lowercase on purpose). The description of its purpose required reading the javadoc for the class at https://github.com/apache/ant/blob/014e94e5d1e289acaf8a4e6e7234662c065d48b2/src/main/allow.java#L30 in combination with JEP 411 at https://openjdk.org/jeps/411

so we need to make sure that any repackaging of ant still works with the scripts and the unusual workaround of having `allow.class` in the default package across multiple versions of Java.

**Comment by jonahgraham** [comment]
Hmm - allow.java has been removed in latest ant master branch, so I don't know what the state of the weird workarounds for security manager in ant currently is. Let me know if you need more research.

**Comment by merks** [comment]
Indeed there is no such thing in the jars for 1.10.14

My plan is to build the update site, and then to test it with the Platform.  I'll first try some things out locally and then I will modify their *.target to use the nightly build and run the verification.

At this point I have replaced all the Platform's use of legacy Orbit/sites bundles and ant will be the last dependency to migrate to Maven BND...

Of course my goal is to have this in place for their M1 build....

**Comment by merks** [comment]
I was able to test the newly created version org.apache.ant 1.10.14 locally with the Platform:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/3447dd2a-91d3-4bee-bcf1-fceb36308eaa)

With a few small changes to the source code, including a number of unfortunate hard-coded versions in the tests, the testes pass:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/aad9d6a4-3133-4f4c-b3f9-edcd681c53be)

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/c68633b1-faf5-4d09-a7f6-21d1a471bedf)

This is the only "breakage":

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/f2a099d6-a986-4fce-872b-6cde03c7d8d5)

@jonahgraham 

Do you see any problems with producing earlier Orbit milestones so that I can get the platform migrated well ahead of their M1 next week?  I really don't want to point that their target platform at transient nightly builds or at moving target repositories and I don't want to leave this until next Tuesday either...

FYI  @akurtakov

**Comment by jonahgraham** [comment]
I think it is a great idea to do an early M1 - we can always have an M1a later if needed.

**Comment by merks** [comment]
The 1.10.14 version is available:

- https://download.eclipse.org/tools/orbit/simrel/maven-bnd/milestone/latest
- https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest

**Comment by SarikaSinha** [comment]
@merks 
I am not able to download from https://download.eclipse.org/tools/orbit/simrel/maven-bnd/milestone/latest/
I get 404 Not found for https://repo1.maven.org/maven2/org/eclipse/orbit/ant/1.10.14
Also in Eclipse build we have the following structure, any change on that? 
<img width="292" alt="image" src="https://github.com/eclipse-orbit/orbit-simrel/assets/14090181/fe05e327-b100-4033-b2c7-984d15f5cbbb">

**Comment by HannesWell** [comment]
> Third option is stop providing this "custom" Ant jar. That means changes to Eclipse platform's Ant integration and a notice for downstream consumers. I don't know how long the tentacles of Ant into Eclipse platform (and wider IDE) are, but in the same way we don't try to repackage Maven or Gradle to make them bundles (AFAIK!), maybe we should stop for Ant.

Actually we do repackage the maven jars in m2e in the [org.eclipse.m2e.maven.runtime](https://github.com/eclipse-m2e/m2e-core/tree/master/org.eclipse.m2e.maven.runtime) 🤐😅
It's a little masterpiece of a maven build but ensure the integrity of all the bundles and prevents the flexibility of OSGi being applied to that set of jars so that it is ensured that only those jars intended to run together form a maven runtime.
At the same time it also acts as most complex use case and demo of M2E's PDE integration (with that you can use regular Maven projects just like PDE Plugin Projects if they use the bnd-maven-plugin or maven-bundle-plugin to generate their MANIFEST.MF).
