### ISSUE TITLE
Incompatible Google Closure compiler version change

### ISSUE THREAD

**Issue by nitind** [eclipse-orbit/orbit-simrel#18]
The prior Orbit Aggregation release and latest milestone, at the moment, have the ancient com.google.javascript_0.0.20160315.v20161124-1903 (as Closure Compiler). Around 2 days ago, nightly changed over to the very incompatible com.google.javascript 0.0.20230802.v20230927-1600 (JSDT can not compile against it, and does not find the old version explicitly listed in its feature.xml). Which one should be expected in M1?

**Comment by merks** [comment]
You can always find such a thing this way:

https://wiki.eclipse.org/Eclipse_Oomph_Authoring#How_to_find_a_P2_repository_at_Eclipse_using_the_Repository_Explorer

You are the only one using that thing:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/839ab112-42ff-47ea-88ae-d880e7cde02b)

And yes, I know there are issues that I raised and hoped to bring to your attention quite some time ago:

https://github.com/eclipse-orbit/orbit-simrel/issues/9

I am aggregating from https://download.eclipse.org/tools/orbit/downloads/drops/N20230908195041/repository/ but at this point, I've excluded all but one with replacements, so you can get "missing" things from there.

I'm sure that many people will be using old repositories to consume and to contribute old things.  You can lead a horse to water...

I expect you'll need to do that for this case until you or someone has time to update to the latest Javascript syntax.  Sorry for that.  But it doesn't make sense to keep providing old things when there are new things.  Old things can come from old repos if necessary, as in this case...

**Comment by merks** [comment]
I don’t think I quite answered your question. The current milestone latest is used by the platform and presumably by others.  What you see in nightly will be what’s in the next milestone which I hope to do as an early preview right after m1 is done this week.

**Comment by merks** [comment]
I think it doesn't make sense to provide a 2016 version of that bundle.   Sorry about that.
