### ISSUE TITLE
Include an Eclipse-SourceReferences header in the manifest?

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-orbit/orbit-simrel#21]
I think that this request makes sense. Feel free to correct me if I'm horribly, horribly wrong.

As part of the process of bundlifying modules, does it make sense to include an `Eclipse-SourceReference` entry in the header that just points to the source JAR? I've observed that this isn't included in at least the handful of bundles that I checked.

I'm thinking of how this might be used in a scenario where the source bundles have not be added to the configuration.

I assume that, the existence of an `scm` scheme suggests that other schemes are possible. My search-fu has, unfortunately, failed me thus far. Whether or not the IDE can currently make sense of the scheme is a separate problem.

**Comment by jonahgraham** [comment]
The big change in orbit is that we don't touch the jar file in most cases but instead use the jar unmodified from maven central. The metadata (artifacts/content) xml files have the GAV in them though. Not sure if there is already a simple way to extract that, but if it sounds useful let me know and we can document how to extract that for your purposes.

I hope I understood your request properly.

**Comment by merks** [comment]
I see `Eclipse-SourceReferences` references in bundles built by Tycho from known source:

> Eclipse-SourceReferences: scm:git:https://git.eclipse.org/r/cdt/org.eclipse.cdt;path="core/org.eclipse.cdt.core.win32.x86_64";commitId=c34816028c30cd60a49cd492f0f20a7f8fa28a27

That's configured like this in a pom.xml:
```
<tycho.scmUrl>scm:git:https://github.com/eclipse-platform/eclipse.platform.common.git</tycho.scmUrl>
```

Such things point into a source code repository, not to a source jar. Moreover, we do not, in general, know this information (scm source) for things coming directly from Maven.

_______

The following is all the information we have about the artifacts being pulled from Maven Central:

- https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-bnd/tp/MavenBND.target
- https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-osgi/tp/Maven.target

The build does generally generate source bundles for all these things too, but those sources also come from Maven Central.

Note that for the BND recipes, i.e., those things for which we (Tycho) do modify the jar, each contain the original GAV, e.g.,
```
Eclipse-Wrapped-Bundle: com.github.jnr:jnr-a64asm:1.0.0
```
Of course a source link can be synthesized from the GAV as Dash already generally does:

> https://repo1.maven.org/maven2/com/github/jnr/jnr-a64asm/1.0.0/jnr-a64asm-1.0.0-sources.jar

In addition to this, Tycho includes useful information with respect to the GAV in the p2 metadata, i.e., the `maven-wrapped-` properties:
```
<unit id='com.github.jnr.a64asm' version='1.0.0.v20230715-0746' singleton='false' generation='2'>
  <update id='com.github.jnr.a64asm' range='[0.0.0,1.0.0.v20230715-0746)' severity='0'/>
  <properties size='4'>
    <property name='org.eclipse.equinox.p2.name' value='Bundle com.github.jnr : jnr-a64asm'/>
    <property name='maven-wrapped-groupId' value='com.github.jnr'/>
    <property name='maven-wrapped-artifactId' value='jnr-a64asm'/>
    <property name='maven-wrapped-version' value='1.0.0'/>
  </properties>
...
</unit>
```
You can see here that the full mapping between BSN/version and corresponding GAV is available, and from that a source artifact on Maven Central can be located.

_________

I think it would be helpful to understand better what information Dash is able to look at.

For example, I believe that to publish to maven central, the jar must include a pom.xml like this:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/20b3c067-2d60-409b-9db7-5fefd6b05d40)

You can see that much useful information is available in that pom.xml.

So my sense is that what's needed to track down source is available already in multiple different forms and likely another form isn't actually needed.

**Comment by msohn** [comment]
Yes, Maven central requires that the pom.xml contains the URL to the SCM system where source code is available.
See https://central.sonatype.org/publish/requirements/
