### ISSUE TITLE
Please include caffeine

### ISSUE THREAD

**Issue by gnl42** [eclipse-orbit/orbit-simrel#22]
caffeine is a "drop in" alternative for guavas CacheBuilder and friends, in fact guava recommends it over it's own cache code.

com.github.ben-manes.caffeine:caffeine:3.1.8

Thanks
   George

**Comment by merks** [comment]
It's available here now and will of course be in the next milestone:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest

**Comment by gnl42** [comment]
I'm probably doing something very stupid, but I'm unable to find caffeine when I add the simrel site to the target file. All I see are the features. None of the bundles show up in the list of items available???

```
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest"/>
		</location>

```

**Comment by merks** [comment]
I'm not sure exactly where/how you are looking.  In the repository explorer you see this by default:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/a8793c70-3fd8-4951-9ecd-2aea24e39912)

You need to switch to Expert mode to see the detailed content:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/dbee5554-35de-498f-804a-f831c4c59a9c)

I don't know if PDE shows such details...

**Comment by gnl42** [comment]
I see this with the target editor:
![image](https://github.com/eclipse-orbit/orbit-simrel/assets/66577321/2eabb711-a746-412e-a324-f7ab902b947f)

all I see are the features. And I can't find any way of adding caffeine to my target file.

What is different about this simrel repository compared to the maven-bnd and the maven-osgi ones?

Sorry, this is all still very much black magic to me.

**Comment by merks** [comment]
Yes, I noticed that too.  That seems very unhelpful to me.  I very much dislike editing a *.target file which is why in all my projects I prefer to let it me generated for me so that I never have to edit it.  I use the poor-man's approach.  I use the Repository Explore to find what I want, double-click it to open the details, and then copy the id from there.  Then I paste into the target

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/834cb741-f264-4ced-b08e-43d62185813d)

Then I test that it's done correct on the main tab

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/7e792c05-3527-4ad0-81e3-723bb6fcb1d3)


```
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest"/>
			<unit id="com.github.ben-manes.caffeine" version="0.0.0"/>
		</location>
```

It would probably be good if I create an early milestone so that you can use  https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12 instead for all the new Orbit dependencies...

**Comment by gnl42** [comment]
Dag nab it! Missed it by that much :( 

I did try to manually add the unit but I just realized that I made a tiny typo.

Thanks, that works

**Comment by gnl42** [comment]
By the way, where do I find the 'Repository Explorer'?

**Comment by merks** [comment]
Quick search:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/7e8ad504-3cbf-40d2-9caa-3cba252ec070)

Window -> Show View -> Other... -> Oomph -> Repository Explorer works too.

**Comment by merks** [comment]
@gnl42 

I would recommend that the target platform use this site:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12

It contains the latest including caffeine.

I.e., replace these
```
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/tools/orbit/simrel/maven-bnd/2023-09/"/>
			<unit id="org.apache.lucene.analysis-common" version="0.0.0"/>
			<unit id="org.apache.lucene.core" version="0.0.0"/>
			<unit id="org.apache.lucene.queries" version="0.0.0"/>
			<unit id="org.apache.lucene.queryparser" version="0.0.0"/>
			<unit id="org.apache.lucene.sandbox" version="0.0.0"/>
		</location>
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/tools/orbit/simrel/maven-osgi/2023-09/"/>
			<unit id="com.google.guava" version="0.0.0"/>
			<unit id="com.google.gson" version="0.0.0"/>
			<unit id="org.mockito.mockito-core" version="0.0.0"/>
		</location>
```
with this:
```
		<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12/"/>
			<unit id="com.github.ben-manes.caffeine" version="0.0.0"/>
			<unit id="org.apache.lucene.analysis-common" version="0.0.0"/>
			<unit id="org.apache.lucene.core" version="0.0.0"/>
			<unit id="org.apache.lucene.queries" version="0.0.0"/>
			<unit id="org.apache.lucene.queryparser" version="0.0.0"/>
			<unit id="org.apache.lucene.sandbox" version="0.0.0"/>
			<unit id="com.google.guava" version="0.0.0"/>
			<unit id="com.google.gson" version="0.0.0"/>
			<unit id="org.mockito.mockito-core" version="0.0.0"/>
			<unit id="com.google.guava" version="0.0.0"/>
			<unit id="com.google.gson" version="0.0.0"/>
			<unit id="org.mockito.mockito-core" version="0.0.0"/>
		</location>
```

**Comment by gnl42** [comment]
Great. Thanks for all you help
