### ISSUE TITLE
Finalize Orbit for 4.30 / 2023-12

### ISSUE THREAD

**Issue by merks** [eclipse-orbit/orbit-simrel#28]
The Platform's RC2/final build is Wednesday so I think it would be best to produce a release repository for the current state of Orbit for contribution to the Platform's target platform:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1392

My generator indicates that there are already a few updates available from Maven Central, but I don't think it's a good idea to incorporate those right before the Platform produces RC2/final and right before the rest of us are producing or have already produced RC1.

@jonahgraham 

I just wanted to check that you agree before I spin the final builds to produce release URLs tomorrow...

**Comment by jonahgraham** [comment]
+1 to doing final build

**Comment by merks** [comment]
These are all final for the release:

- https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.30.0
- https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-12
- https://download.eclipse.org/tools/orbit/simrel/maven-bnd/release/4.30.0
- https://download.eclipse.org/tools/orbit/simrel/maven-bnd/2023-12
- https://download.eclipse.org/tools/orbit/simrel/maven-osgi/release/4.30.0
- https://download.eclipse.org/tools/orbit/simrel/maven-osgi/2023-12
- https://download.eclipse.org/tools/orbit/simrel/maven-sign/release/latest
- https://download.eclipse.org/tools/orbit/simrel/maven-sign/2023-12
- https://download.eclipse.org/tools/orbit/simrel/orbit-legacy/release/4.30.0
- https://download.eclipse.org/tools/orbit/simrel/orbit-legacy/2023-12
