### ISSUE TITLE
Please add jgoodies-common and jgoodies-forms

### ISSUE THREAD

**Issue by ptziegler** [eclipse-orbit/orbit-simrel#36]
For the WindowBuilder project, I'd like to get rid of [org.eclipse.wb.swing.FormLayout.lib](https://github.com/eclipse-windowbuilder/windowbuilder/tree/master/org.eclipse.wb.swing.FormLayout.lib), which contains both jgoodies-common and jgoodies-forms as embedded jars.

Newer versions have become proprietary, so it's unlikely that any fix can be added to the upstream project. Ideally, I'd like to use the latest release, before the project became closed source:

https://mvnrepository.com/artifact/com.jgoodies/jgoodies-common/1.8.1
https://mvnrepository.com/artifact/com.jgoodies/jgoodies-forms/1.9.0

**Comment by merks** [comment]
I was already having a look. Even these are from 2015 if I recall correctly.  I assume you are asking because a BND recipe is needed, right?

**Comment by merks** [comment]
These are now available here:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/f96c58b0-3f45-4200-ba56-d15e75ca854a)

Please verify that they are functional as soon as possible.

Note that these two issue were quickly reviewed and approved:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14176
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14175

But these two "duplicates" are open:

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14174
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/14173

**Comment by ptziegler** [comment]
I tried both out and the test results are very promising. Thanks a lot! 😄
