### ISSUE TITLE
Where is aop-alliance gone

### ISSUE THREAD

**Issue by cdietrich** [eclipse-orbit/orbit-simrel#4]
Hi, where is `<unit id="org.aopalliance" version="1.0.0.v20220404-1927"/>`
gone?

i can see
```
<?xml version="1.0" encoding="UTF-8"?>
<p2:Requirement
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:p2="http://www.eclipse.org/oomph/p2/1.0"
    name="org.eclipse.orbit.maven.aopalliance.feature.group"
    versionRange="[4.29.0.v20230720-0728,4.29.0.v20230720-0728]"/>
```
only
version number seems wired as guice uses 1.0

**Comment by cdietrich** [comment]
junit 4.13.2 also seems to be gone

**Comment by merks** [comment]
It would help if you state where you are looking.

**Comment by merks** [comment]
If you look here you see it:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/3855cc39-bd6d-4b6f-ba50-8f417fd3c611)

Also this:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/5455a055-af00-485c-bf7a-097917ebe2b2)

If you reference a "moving target" repository, you should expect it to change over time...

**Comment by cdietrich** [comment]
arggg. expert mode in repo explorer was off.
can find changed version timestamps now

**Comment by cdietrich** [comment]
now i see the hamcrest problem. what is the solution for that?

**Comment by merks** [comment]
I have done a build for the platform using latest nightly which is the same as https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2023-09/ at the moment:

https://ci.eclipse.org/platform/job/eclipse.platform.releng.aggregator/job/PR-1233/

What exactly is "the hamcrest" problem for you?

**Comment by cdietrich** [comment]
```
Error:  Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.5:validate-classpath (default-validate-classpath) on project org.eclipse.xtend.lib.tests: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.5:validate-classpath failed: org.osgi.framework.BundleException: Bundle org.eclipse.xtend.lib.tests cannot be resolved:org.eclipse.xtend.lib.tests [8]
Error:    Unresolved requirement: Require-Bundle: org.junit; bundle-version="4.13.2"
Error:      -> Bundle-SymbolicName: org.junit; bundle-version="4.13.2.v20230725-0701"
Error:         org.junit [3]
Error:           Unresolved requirement: Import-Package: org.hamcrest; version="1.3.0"
Error:  
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
```

**Comment by merks** [comment]
The org.junit bundles is now like this;
```
Import-Package                          org.hamcrest.core;version="1.3"
                                        org.hamcrest;version="1.3"
Require-Bundle                          org.hamcrest.core;bundle-version="1.3.0";resolution:=optional;visibility:=reexport;x-installation:=greedy
```
So you either need to include org.hamcrest.core in your target platform (so it can greedy resolve) or you need to add package imports for org.hamcrest.core (1.3 or higher) and org.hamcrest 1.3 or higher), or a bundle require for org.hamcrest (2.2) wherever you include org.junit however you are doing that.

**Comment by merks** [comment]
Note that I won't finalize these repositories and their contents for m2 until tomorrow, but today is quickly drawing to a close.

**Comment by cdietrich** [comment]
ok will add hamcrest where i have junit and let builds run overnight.

**Comment by merks** [comment]
The Platform's build works and I've tested that Oomph (which has a generated *.target) can regenerate the target and can do a Tycho build running tests; though I think that's using the org.junit from the platform.

**Comment by cdietrich** [comment]
Xtext build looks good too. Have merged and when master was built will test downstream too

**Comment by merks** [comment]
@cdietrich 

Thanks for the confirmation.   I'm just doing some final cleanups of duplicates that are not in SimRel before producing milestone repositories for use by the Platform.

**Comment by cdietrich** [comment]
Downstream looks good too
