### ISSUE TITLE
Incompatible changes after M3

### ISSUE THREAD

**Issue by cdietrich** [eclipse-orbit/orbit-simrel#41]
Hi @merks. what is the current policy on breaking changes after M3 (in this case guava)

**Comment by merks** [comment]
Can you elaborate on what's breaking?

I think we should try to get this version into the release:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15952

I've already built the nightly Orbit sites to include this and plan to produce a milestone builds with that shortly during the next hour.

**Comment by cdietrich** [comment]
If this appear on 2024-09 simrel Xtext and mwe won’t be able to build a release without me spending extra shifts on top of the extra shifts I have to spend working on Xtext anyway
