### ISSUE TITLE
Apache Batik 1.18

### ISSUE THREAD

**Issue by pcdavid** [eclipse-orbit/orbit-simrel#42]
It's not released yet, but it looks like a new version of Apache Batik [will be released soon](https://lists.apache.org/thread/jbf1zlp259mq9qg3lkgyrvldyp9g27qn), [along with a few other XML Graphics components](https://lists.apache.org/list.html?general@xmlgraphics.apache.org).

**Comment by pcdavid** [comment]
It's released, see https://lists.apache.org/list.html?batik-users@xmlgraphics.apache.org and https://xmlgraphics.apache.org/batik/download.html which mentions:

```xml
<dependency>
  <groupId>org.apache.xmlgraphics</groupId>
  <artifactId>batik-all</artifactId>
  <version>1.18</version>
</dependency>
```

**Comment by pcdavid** [comment]
Not available yet on Maven Central, https://search.maven.org/search?q=g:org.apache.xmlgraphics%20a:batik-all only shows 1.17 at the moment.

**Comment by merks** [comment]
It's there:

https://repo1.maven.org/maven2/org/apache/xmlgraphics/batik-all/1.18/

The orbit updaters/generators look directly at that host for updates.

There is a whole boat load of stuff

![image](https://github.com/user-attachments/assets/cbf16dd3-1ad5-4141-aaa9-a2a081efe6ab)

I've only updated what's already in Orbit along with one new dependencies.  It's currently building:

https://ci.eclipse.org/orbit/job/orbit-simrel-maven-bnd/229/console

That build will kick the aggregation build so I expect that to all be done within the next 15-20 minutes.

Before I committed this, I locally built BIRT against the locally-built org.apache.xmlgraphics updates and ran all the test to check if there are any problems.  That all worked fine.

**Comment by merks** [comment]
It's done and available:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/table.html

**Comment by pcdavid** [comment]
Thank you. I'll try and update GMF Runtime and Sirius as soon as I can, but probably not before next week.

**Comment by merks** [comment]
FYI, there are a large number of iplab issues open:

https://ci.eclipse.org/orbit/job/orbit-simrel-maven-bnd/229/

When those are done, I will do a milestone build and update the Platform to use it.
