### ISSUE TITLE
Please generate report for https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/master/target-platform/mylyn-docs.target

### ISSUE THREAD

**Issue by akurtakov** [eclipse-orbit/orbit-simrel#6]
It would be helpful to get report what's pending update in mylyn-docs.

**Comment by merks** [comment]
Here's the report:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/mylyn-docs/REPORT.md
