### ISSUE TITLE
Need to sign jnilibs for macOS notarization

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-orbit/orbit-simrel#7]
The new version of JFFI contributed [here](https://github.com/eclipse-orbit/orbit-simrel/blob/d3222f558b75f942858fbcb767aabb835ea0e502/maven-osgi/tp/Maven.target#L129-L142) and used by linuxtools (which is included in CPP and Embed CPP package) [here](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/5ed90115802e079bf391b791158133a699e19b86/releng/org.eclipse.linuxtools.target/linuxtools-e4.29.target#L116-L129) causes notarization to fail because the jnilibs are not signed.

In EBR based Orbit we do sign the jnilibs as part of the Orbit process. See [this bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=576947) for reference the last time JFFI failed and [this part of pom.xml](https://github.com/eclipse/orbit/blob/ed65f7abb8d967deebcba6ac1eb1a16efd56f759/releng/mavenparent/pom.xml#L196-L234) for how we sign the jnilibs.

Note that JNA needed signing in the past, but Apple's notarization processes sometimes look arbitrarily deep in jars and provides a moving target that we need to chase regularly. Also, the JNA maintainers [are not interested](https://github.com/java-native-access/jna/issues/1306#issuecomment-772696095) in providing signed jnilibs in their release.

<details>
<summary>full json of error</summary>

```json
{
  "logFormatVersion": 1,
  "jobId": "b0fe30eb-7a90-48a0-9b26-de50880fcd81",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "eclipse-cpp-2023-09-M2-macosx-cocoa-aarch64-6370600730443560226.dmg",
  "uploadDate": "2023-08-03T18:24:52Z",
  "sha256": "320d3da6e1e89a841ba4e796f083ddec1c66e81bb11a1c6c9ab444443b2bdf84",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "eclipse-cpp-2023-09-M2-macosx-cocoa-aarch64-6370600730443560226.dmg/Eclipse.app/Contents/Eclipse/plugins/com.github.jnr.jffi.native_1.3.11.jar/jni/Darwin/libjffi-1.2.jnilib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eclipse-cpp-2023-09-M2-macosx-cocoa-aarch64-6370600730443560226.dmg/Eclipse.app/Contents/Eclipse/plugins/com.github.jnr.jffi.native_1.3.11.jar/jni/Darwin/libjffi-1.2.jnilib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eclipse-cpp-2023-09-M2-macosx-cocoa-aarch64-6370600730443560226.dmg/Eclipse.app/Contents/Eclipse/plugins/com.github.jnr.jffi.native_1.3.11.jar/jni/Darwin/libjffi-1.2.jnilib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "eclipse-cpp-2023-09-M2-macosx-cocoa-aarch64-6370600730443560226.dmg/Eclipse.app/Contents/Eclipse/plugins/com.github.jnr.jffi.native_1.3.11.jar/jni/Darwin/libjffi-1.2.jnilib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "arm64"
    }
  ]
}
```

</details>

**Comment by jonahgraham** [comment]
FYI: @akurtakov @merks

**Comment by merks** [comment]
@akurtakov 

I assume, but wanted to confirm, that if/when Orbit provides a version with signed libraries, that you will switch linuxtools to use that instead.

**Comment by akurtakov** [comment]
Sure will do

**Comment by merks** [comment]
@jonahgraham

Looking in Orbit, I see these

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/650bab3e-2cbf-4df3-bff5-8af75c15669e)

I assume that this  version, which is in the CDT, package is not also a problem:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/3eb01056-a36e-4466-8f36-1df56ca7af14)

**Comment by jonahgraham** [comment]
I don't know why at the moment Apple isn't complaining about JNA's jnilibs. It has in the past, and may again in the future.

**Comment by merks** [comment]
Maybe the jna ones are signed?  Is there a way to tell?  

These the the exact jars:

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11-native.jar
https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar

If the mac libraries aren't signed probably the Windows *.dll aren't signed as well, but maybe no one notices nor complains?

**Comment by jonahgraham** [comment]
If they are signed I would be surprised because the JNA maintainers in the past said they [are not interested](https://github.com/java-native-access/jna/issues/1306#issuecomment-772696095) in providing signed jnilibs in their release. I don't know how to test on a non-mac machine if they are signed, and I don't have a mac machine to check with.

> If the mac libraries aren't signed probably the Windows *.dll aren't signed as well, but maybe no one notices nor complains?

Correct :-) The Apple notarization process makes us do it.

**Comment by merks** [comment]
So it's probably better to plan ahead to avoid risk?  If notarization suddenly fails late in a release cycle, that could put a damper on things.  I think it will be especially important for these bundles not to be included in any features.

Also, if we are going to be modifying the jar's content, which is the entire point/goal here, I think we need to be careful not to use exactly the same (unqualified) version (or we need to use a different bundle symbolic name).

**Comment by akurtakov** [comment]
https://openjdk.org/jeps/442 - as soon as it's final we should start using it and stop dealing with jni/jna/jnr .

**Comment by jonahgraham** [comment]
> So it's probably better to plan ahead to avoid risk? 

Yes I agree. We have had some late failures in the past too since Apple is a moving target, e.g. m2e has (or had) an embedded jnilib that Hannes signed in the past https://github.com/eclipse-m2e/m2e-core/issues/591

Notarization does not run on EPP for each build, but I (or you) can manually trigger it at anytime to see if there is a problem. Run https://ci.eclipse.org/packaging/job/notarize-downloads/ (but probably best disable https://ci.eclipse.org/packaging/job/simrel.epp-tycho-build/ so that the staging repo isn't changed while notarization is running). IIRC Notarization runs on Platform on each build.

**Comment by merks** [comment]
> https://openjdk.org/jeps/442 - as soon as it's no longer preview in some JVM version (hopefully 22) we should start using it and stop dealing with jni/jna/jnr .

It might be a case of getting everyone else to start using it too.

**Comment by merks** [comment]
The bundles with signed native libraries, including signed *.dll, are available here:

https://download.eclipse.org/tools/orbit/simrel/maven-sign/

They are also available in the aggregation:

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/nightly/latest

In the current SimRel, these are the strict requirements on these two things.

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/15b4894b-fdd5-4272-9db9-c670fa25ebdd)

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/c4a5a3f3-dd14-4672-a6c2-216f087ebc65)

Directly reusing com.sun.jna 5.13.0 as a Maven dependency is quite popular:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/f0a6a61b-9095-43ea-af56-285257443d21)

Only passage @ruspl-afed locks in that specific exact version.

@jonahgraham 

How best do we ensure that we don't end up with the unsigned versions in the aggregation?  I could add a rule to specifically exclude them, but we probably ought to get the contributing projects to use these signed versions instead...

It is possible to create an exclusion rule, though it's marked as an error when placed on a repository that doesn't contain a matching IU:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/3adb896b-4135-48e8-8f26-0c334677abe1)

It would fail like this:

> Cannot complete the install because some dependencies are not satisfiable
> Software being installed: validationSet_main 1.0.0
> Cannot satisfy dependency:
> From: mappedRepo_download.eclipse.org_oomph_drops_milestone_S20230802-094623-1.30.0-M2 1.0.0
> To: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_oomph_drops_milestone_S20230802-094623-1.30.0-M2_rejections [1.0.0,1.0.0]
> Cannot satisfy dependency:
> From: mappedRepo_download.eclipse.org_oomph_drops_milestone_S20230802-094623-1.30.0-M2_rejections 1.0.0
> To: org.eclipse.equinox.p2.iu; com.sun.jna [5.13.0,5.13.0]
> Cannot satisfy dependency:
> From: mappedRepo_download.eclipse.org_passage_updates_milestone_2.9.0-M2_ldc 1.0.0
> To: org.eclipse.equinox.p2.iu; org.eclipse.passage.ldc.feature.feature.group [2.9.0.v20230701-2026,2.9.0.v20230701-2026]
> Cannot satisfy dependency:
> From: Passage LDC 2.9.0.v20230701-2026 (org.eclipse.passage.ldc.feature.feature.group 2.9.0.v20230701-2026)
> To: org.eclipse.equinox.p2.iu; org.eclipse.passage.lic.define.feature.feature.group [2.9.0.v20230701-2026,2.9.0.v20230701-2026]
> Cannot satisfy dependency:
> From: Passage LIC Define 2.9.0.v20230701-2026 (org.eclipse.passage.lic.define.feature.feature.group 2.9.0.v20230701-2026)
> To: org.eclipse.equinox.p2.iu; org.eclipse.passage.lic.execute.feature.feature.group [2.9.0.v20230701-2026,2.9.0.v20230701-2026]
> Cannot satisfy dependency:
> From: Passage LIC Execute 2.9.0.v20230701-2026 (org.eclipse.passage.lic.execute.feature.feature.group 2.9.0.v20230701-2026)
> To: org.eclipse.equinox.p2.iu; org.eclipse.passage.lic.oshi.feature.feature.group [2.9.0.v20230701-2026,2.9.0.v20230701-2026]
> Cannot satisfy dependency:
> From: Passage LIC OSHI 2.9.0.v20230701-2026 (org.eclipse.passage.lic.oshi.feature.feature.group 2.9.0.v20230701-2026)
> To: org.eclipse.equinox.p2.iu; com.sun.jna [5.13.0,5.13.0]
> Cannot satisfy dependency:
> From: validationSet_main 1.0.0
> To: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_oomph_drops_milestone_S20230802-094623-1.30.0-M2 [1.0.0,1.0.0]
> Cannot satisfy dependency:
> From: validationSet_main 1.0.0
> To: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_passage_updates_milestone_2.9.0-M2_ldc [1.0.0,1.0.0]

**Comment by akurtakov** [comment]
@merks Is everything ready to switch Linux Tools to signed jffi ?

**Comment by merks** [comment]
Yes, both nightly builds  (maven-sign and orbit-aggregation) contain the new IU with a qualifier:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/0aa0c886-bb06-4000-9ebb-de575082815e)

**Comment by jonahgraham** [comment]
> @jonahgraham
> 
> How best do we ensure that we don't end up with the unsigned versions in the aggregation? I could add a rule to specifically exclude them, but we probably ought to get the contributing projects to use these signed versions instead...
> 
> It is possible to create an exclusion rule, though it's marked as an error when placed on a repository that doesn't contain a matching IU:

@merks  I assume with @akurtakov updating Linux Tools and you adding exclusion rule we'll have the correct version in SimRel soon? If so, we can try to notarize the nightly build of EPP.

**Comment by merks** [comment]
With this change

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/203578

I've contributed (temporarily) both new bundles to SimRel aggregation.  The new jffi.native version is the only one in the aggregation:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/6e43407e-4b8f-4035-ac3a-e0a87f35bc62)

So once the aggregation completes

https://ci.eclipse.org/simrel/job/simrel.runaggregator.pipeline/

 you can test if notarization works. 

Until passage doesn't lock in the unqualified version of com.sun.jna, we can't do much about that, but the newer version is there:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/208716/c06b1cf0-8e76-4e20-8721-d412763fcc9c)

**Comment by jonahgraham** [comment]
Thanks Ed. [EPP build](https://ci.eclipse.org/packaging/job/simrel.epp-tycho-build/2892/) is running, when done I will try to notarize it and report back,

**Comment by jonahgraham** [comment]
Notarized successfully.

**Comment by jonahgraham** [comment]
The new jffi exposes an issue. *External Plug-in Libraries* project that is auto-managed by JDT(?) has an error:

`Cannot nest 'scratch/eclipse/src/cdt/workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/com.github.jnr.jffi.native_1.3.11.v20230807-0900/jni' inside library 'scratch/eclipse/src/cdt/workspace/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/com.github.jnr.jffi.native_1.3.11.v20230807-0900'`

For some reason jffi appears as an unpacked bundle, perhaps due to `Bundle-NativeCode` not really sure?

**Comment by jonahgraham** [comment]
Steps to reproduce last comment:

1. Set target platform to something containing jffi
2. "Add all plug-ins to java workspace scope" (from Ctrl-3)
3. Observe error in Problems view:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/679236/13dfc891-9330-485c-b72b-7cf730c057dd)

Good thing is I found an easy workaround for now, right-click on the bundle in the plug-ins view and choose remove from java workspace scope:

![image](https://github.com/eclipse-orbit/orbit-simrel/assets/679236/6480cf7b-8b6e-4878-914d-57e70edbdb60)

**Comment by jonahgraham** [comment]
I think what causes the issue is having `Bundle-Classpath` in the bundle be two directories which are nested:

```java
Bundle-ClassPath: .,jni
```

Is this a JDT bug, or a JFFI bug?

**Comment by merks** [comment]
The ebr version looked like this:
```
Archiver-Version                        Plexus Archiver
Automatic-Module-Name                   com.github.jnr.jffi.native
Build-Jdk-Spec                          11
Bundle-ClassPath                        .
                                        jni/
Bundle-Description                      Java Foreign Function Interface - Native Libraries
Bundle-License                          http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion                  2
Bundle-Name                             %bundleName
Bundle-SymbolicName                     com.github.jnr.jffi.native
Bundle-Vendor                           %bundleVendor
Bundle-Version                          1.3.9.v20221215-1656
Created-By                              Eclipse Bundle Recipe Maven Plug-in
Export-Package                          Darwin;version="1.3.9"
                                        aarch64-FreeBSD;version="1.3.9"
                                        aarch64-Linux;version="1.3.9"
                                        arm-Linux;version="1.3.9"
                                        i386-Linux;version="1.3.9"
                                        i386-SunOS;version="1.3.9"
                                        i386-Windows;version="1.3.9"
                                        mips64el-Linux;version="1.3.9"
                                        ppc-AIX;version="1.3.9"
                                        ppc64-AIX;version="1.3.9"
                                        ppc64-Linux;version="1.3.9"
                                        ppc64le-Linux;version="1.3.9"
                                        s390x-Linux;version="1.3.9"
                                        sparcv9-Linux;version="1.3.9"
                                        sparcv9-SunOS;version="1.3.9"
                                        x86_64-DragonFlyBSD;version="1.3.9"
                                        x86_64-FreeBSD;version="1.3.9"
                                        x86_64-Linux;version="1.3.9"
                                        x86_64-OpenBSD;version="1.3.9"
                                        x86_64-SunOS;version="1.3.9"
                                        x86_64-Windows;version="1.3.9"
Fragment-Host                           com.github.jnr.jffi
Manifest-Version                        1.0
Originally-Created-By                   Apache Maven Bundle Plugin
```
The new version like this:
```
Archiver-Version                        Plexus Archiver
Automatic-Module-Name                   org.jnrproject.jffi.nativelibs
Bnd-LastModified                        1678551168976
Build-Jdk                               11.0.17
Built-By                                headius
Bundle-ClassPath                        .
                                        jni
Bundle-Description                      Java Foreign Function Interface - Native Libraries
Bundle-License                          http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion                  2
Bundle-Name                             jffi
Bundle-SymbolicName                     com.github.jnr.jffi.native
Bundle-Version                          1.3.11.v20230807-0900
Created-By                              Apache Maven Bundle Plugin
Fragment-Host                           com.github.jnr.jffi
Manifest-Version                        1.0
Require-Bundle                          com.github.jnr.jffi
Tool                                    Bnd-2.1.0.20130426-122213
```
The ebr versions exported packages look kind of bogus, given these can't even be package names.

The only classpath difference is the  / on the jni.  I think the MANIFEST.MF must also be on the classpath, so I don't think it's wrong the way it is.

But I could modify the recipe to add the /?

**Comment by merks** [comment]
Oh, no, I can't change the recipe because this is doesn't use a recipe.  It's exactly like this in Maven central:

https://repo1.maven.org/maven2/com/github/jnr/jffi/1.3.11/jffi-1.3.11.jar

**Comment by merks** [comment]
Perhaps I could change it because there is a post-processing step when the libraries are being signed, but it's no clear why the / would make JDT happy/happier...

**Comment by akurtakov** [comment]
Is this one done or there is still some problem that I have to look at ?

**Comment by merks** [comment]
I think we are done here now.

**Comment by DanielZanchi** [comment]
I am having the same problem with a non sandboxed java app that is using JNA 5.10. 
This is part of my `ant` script to create and sign the dmg:
`
<target name="macosxSignedInstaller" depends="macosxBundle" description="Builds install/app-name-version-macosx.dmg archive">
		
		
		<exec executable="find" failonerror="yes">
			<arg value="install/macosx/app-name-${version}/app-name.app/Contents" />
			<arg value="-type" />
			<arg value="f" />
			<arg value="(" />
			<arg value="-name" />
			<arg value="*.dylib" />
			<arg value="-or" />
			<arg value="-name" />
			<arg value="app-name" />
			<arg value="-or" />
			<arg value="-name" />
			<arg value="JavaNativeFoundation" />
			<arg value="-or" />
			<arg value="-name" />
			<arg value="jspawnhelper" />
			<arg value="-or" />
			<arg value="-name" />
			<arg value="*.jar" />
			<arg value=")" />
			<arg value="-exec" />
			<arg value="codesign" />
			<arg value="-v" />
			<arg value="-f" />
			<arg value="-s" />
			<arg value="${certificateName}" />
			<arg value="--timestamp" />
			<arg value="--options=runtime" />
			<arg value="--entitlements" />
			<arg value="install/macosx/app-name.entitlements" />
			<arg value="{}" />
			<arg value=";" />
		</exec>

		
		<exec executable="codesign" failonerror="yes">
			<arg value="-f" />
			<arg value="-s" />
			<arg value="${certificateName}" />
			<arg value="--options=runtime" />
			<arg value="--entitlements" />
			<arg value="install/macosx/app-name.entitlements" />
			<arg value="install/macosx/app-name-${version}/app-name.app" />
		</exec>

		
		<delete file="install/app-name-${version}-macosx.dmg" />
		<exec executable="hdiutil" failonerror="yes">
			<arg value="create" />
			<arg value="-fs" />
			<arg value="HFS+" />
			<arg value="-format" />
			<arg value="UDBZ" />
			<arg value="-srcfolder" />
			<arg value="install/macosx/app-name-${version}" />
			<arg value="install/app-name-${version}-macosx.dmg" />
		</exec>
		
		
		<delete dir="build" />
		<delete dir="install/macosx/app-name-${version}" />

		<echo message="signed install/app-name-${version}-macosx.dmg ready for ftp" />
	</target>
`

after i run the notarize command:
`
xcrun notarytool
`
 
that fails with this output:
` {
  "logFormatVersion": 1,
  "jobId": "a2bee5b4-ee40-46fb-be7f-38d2c1c0a456",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "app-name-7.5.4-macosx.dmg",
  "uploadDate": "2025-02-04T16:06:22.286Z",
  "sha256": "425f94928ca7b009ec3f91abf01e54c6d4c2a0749bea40c1855dcc6aa17e96cc",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "app-name-7.5.4-macosx.dmg/app-name.app/Contents/app/jna-5.10.0.jar/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib",
      "message": "The binary is not signed with a valid Developer ID certificate.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "app-name-7.5.4-macosx.dmg/app-name.app/Contents/app/jna-5.10.0.jar/com/sun/jna/darwin-aarch64/libjnidispatch.jnilib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "arm64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "app-name-7.5.4-macosx.dmg/app-name.app/Contents/app/jna-5.10.0.jar/com/sun/jna/darwin-x86-64/libjnidispatch.jnilib",
      "message": "The binary is not signed.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087721",
      "architecture": "x86_64"
    },
    {
      "severity": "error",
      "code": null,
      "path": "app-name-7.5.4-macosx.dmg/app-name.app/Contents/app/jna-5.10.0.jar/com/sun/jna/darwin-x86-64/libjnidispatch.jnilib",
      "message": "The signature does not include a secure timestamp.",
      "docUrl": "https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087733",
      "architecture": "x86_64"
    }
  ]
}`

**Comment by jonahgraham** [comment]
@DanielZanchi macOS notarization can be a bit of a whack-a-mole game as items that used to notarize suddenly stop as Apple adds more and more checks. 

Thanks for the  heads-up. Eclipse signing and notarization is working fine at the moment (from Jan 30):

```
{
"path": "eclipse-committers-2025-03-M2-macosx-cocoa-x86_64-7775373886969142494.dmg/Eclipse.app/Contents/Eclipse/plugins/com.sun.jna_5.16.0.v20241222-1200/com/sun/jna/darwin-x86-64/libjnidispatch.jnilib",
"digestAlgorithm": "SHA-256",
"cdhash": "8984888b12326f8617ba5b36d522cb039b11c455",
"arch": "x86_64"
},
```

(full [log](https://ci.eclipse.org/packaging/job/notarize-downloads/209/artifact/eclipse-committers-2025-03-M2-macosx-cocoa-x86_64.dmg-tonotarize.log))
